Revert "mkinitcpio: fix behavior generatedir"
This reverts commit 01c71e23743ceab44e1fd5bd8cbbe01b9f1aaa77.

This commit changed the semantics of initialize_buildroot and made some
invocations of the function leave garbage in /tmp/mkinitcpio.XXXXXX,
especially during tests. Restore the previous behaviour, and instead
copy the built tree to _opttargetdir if the flag is passed. This should
keep things working for mkinitcpio-generate-shutdown-ramfs.service.

Alternate working directories are always passed with -t, which exports a
different TMPDIR, so there should be no need for the second argument on
initialize_buildroot.

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1147,18 +1147,20 @@ initialize_buildroot() {
     # creates a temporary directory for the buildroot and initialize it with a
     # basic set of necessary directories and symlinks
 
-    local kernver="$1" generatedir="$2" workdir arch buildroot osreleasefile root
+    local kernver="$1" workdir="$2" arch buildroot osreleasefile
     arch="$(uname -m)"
 
-    if ! workdir="$(mktemp -d --tmpdir mkinitcpio.XXXXXX 2>/dev/null)"; then
-        error 'Failed to create temporary working directory in %s' "${TMPDIR:-/tmp}"
-        return 1
+    if [[ -z "$workdir" ]]; then
+        if ! workdir="$(mktemp -d --tmpdir mkinitcpio.XXXXXX 2>/dev/null)"; then
+            error 'Failed to create temporary working directory in %s' "${TMPDIR:-/tmp}"
+            return 1
+        fi
     fi
     earlyroot="$workdir/early"
-    buildroot="${generatedir:-$workdir/root}"
+    buildroot="$workdir/root"
 
-    if [[ ! -w "${generatedir:-$workdir}" ]]; then
-        error 'Unable to write to build root: %s' "$buildroot"
+    if [[ ! -w "$workdir" ]]; then
+        error 'Unable to write to working directory: %s' "$workdir"
         return 1
     fi
 
