Fix #188

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -2,6 +2,15 @@
 # SPDX-License-Identifier: GPL-2.0-only
 
 shopt -s extglob
+dir="temp"
+
+new_temp() {
+    if [ "$dir" = "temp" ] && ! dir="$(mktemp -d --tmpdir mkinitcpio.XXXXXX 2>/dev/null)"; then
+        error 'Failed to create temporary working directory in %s' "${TMPDIR:-/tmp}"
+        return 1
+    fi
+    return 0
+}
 
 parseopts() {
     local opt='' optarg='' i='' shortopts="$1"
@@ -1149,9 +1158,10 @@ initialize_buildroot() {
 
     local kernver="$1" generatedir="$2" workdir arch buildroot osreleasefile root
     arch="$(uname -m)"
-
-    if ! workdir="$(mktemp -d --tmpdir mkinitcpio.XXXXXX 2>/dev/null)"; then
-        error 'Failed to create temporary working directory in %s' "${TMPDIR:-/tmp}"
+    new_temp
+    var=$?
+    workdir="$dir"
+    if [ "$var" == "1" ]; then
         return 1
     fi
     earlyroot="$workdir/early"
